[package]
name = "template"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.12"
combinations="0.1.0"
regex = "1.10"
roots = "0.0.8"
anyhow = "1.0.75"
rand = "0.8.5"
