[package]
name = "advent_of_code_template"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
combinations="0.1.0"
once_cell = "1.12"
regex = "1.5.4"
